<html lang="en-US" prefix="og: http://ogp.me/ns#">
<?php wp_head();?>
<head>
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">

<meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" as="style" onload="this.onload=null;this.rel='stylesheet'" id="ao_optimized_gfonts" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A200%2C300%2C400%2C600%2C700%2C900%2C200italic%2C300italic%2C400italic%2C600italic%2C700italic%2C900italic%7CGFS+Didot%3A400">
</head>
	
	<body class="home blog" data-gr-c-s-loaded="true" data-pin-hover="true"><header id="header"><div class="container"><div id="logo"><h1><a href="/"><img src="https://deedeesblog.com/wp-content/uploads/2020/03/Deedeesblog-new-logo-202-for-blog-BW.png" alt="BellaNaija Weddings"></a></h1> <button type="button"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAG1JREFUWIXt1EEKgDAMRNGv95Oi999r9RB1VXSRCqWkKsyDricJdEBELjMQgeT8diBYA/QIzy/m0PE2QKq4ViszKwAr/ttvwOSylvyeemCouFarYg/0uIJ6QIoW4ODFHugR/tgD5t90oh4Q+Y4T1VL2Pm2VYFoAAAAASUVORK5CYII=" alt="Menu"></button><div class="clearfix"></div></div><div id="main-search" class="clearfix"><div class="main-search-form"><form role="search" method="get" id="searchform" action="<?php echo home_url(); ?>"> <input type="text" placeholder="Search..." name="s" id="s"> <span class="search"><i class="fa fa-search"></i></span></form></div></div></div><div id="mobile-nav" class="clearfix"><div id="nav-wrapper"><ul id="menu-primary" class="main-menu menu"><li id="menu-item-1163128" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1163128"><a href="/category/relationship-hack/">Hack</a></li><li id="menu-item-1163129" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1163129"><a href="/category/relationship-how-tos/">How Tos</a></li><li id="menu-item-1163031" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1163031"><a href="/category/deedees-tv/">TV</a></li><li id="menu-item-1163034" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1163034"><a href="/category/lifestyle/">Lifestyle</a></li><li id="menu-item-11" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-11"><a href="/category/soul-lounge/">Soul Lounge</a></li><li id="menu-item-1163032" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1163032"><a href="/category/counseling-tips/">Counseling Tips</a></li></ul></div></div></header>
		<br>